// ignore_for_file: public_member_api_docs, sort_constructors_first
class NearbyPlaceModel {
  final String image;
  final String name;
  final String distance;
  final String description;
  final String bus;
  final String bike;
  final String car;
  final String walk;
  final String type;

  NearbyPlaceModel({
    required this.image,
    required this.name,
    required this.distance,
    required this.description,
    required this.bus,
    required this.bike,
    required this.car,
    required this.walk,
    required this.type,
  });
}

List<NearbyPlaceModel> nearbyPlaces = [
  NearbyPlaceModel(
    image: "assets/places/BayfrontPark.jpg",
    name: "Bayfront Park",
    description: "Found along the banks of Lake Ontario, Bayfront Park is a 40-acre park in the West-end of Hamilton Harbour. Connected to the beautiful Hamilton Waterfront Trail, specifically the Desjardins Trail, the park is a great place to start or end a waterfront stroll. It includes a lower shoreline walkway, naturalized areas of shrubs, trees, and wildflowers, a public boat launch, numerous benches, picnic areas, a natural grass amphitheatre and a beach volleyball court.",
    distance: "5 km",
    car: "15 min",
    bus: "50 min",
    bike: "20 min",
    walk: "1h 15 min",
    type: "park",
  ),
  NearbyPlaceModel(
    image: "assets/places/ChristieLake.jpg",
    name: "Christie Lake",
    description: "Blah Blah Blah",
    distance: "8 km",
    car: "15 min",
    bus: "50 min",
    bike: "20 min",
    walk: "1h 15 min",
    type: "lake",
  ),
  NearbyPlaceModel(
    image: "assets/places/CootesParadiseTrail.jpg",
    name: "Cootes Paradise Trail",
    description: "Blah Blah Blah",
    distance: '2 km',
    car: "15 min",
    bus: "50 min",
    bike: "20 min",
    walk: "1h 15 min",
    type: "trail",
  ),
  NearbyPlaceModel(
    image: "assets/places/GagePark.jpg",
    name: "Gage Park",
    description: "Blah Blah Blah",
    distance: "10 km",
    car: "15 min",
    bus: "50 min",
    bike: "20 min",
    walk: "1h 15 min",
    type: "park",
  ),
  NearbyPlaceModel(
    image: "assets/places/TiffanyFalls.jpg",
    name: "Tiffany Falls",
    description: "Blah Blah Blah",
    distance: "15 km",
    car: "15 min",
    bus: "50 min",
    bike: "20 min",
    walk: "1h 15 min",
    type: "waterfalls",
  ),
  NearbyPlaceModel(
    image: "assets/places/WaterfrontTrail.jpg",
    name: "Waterfront Trail",
    description: "Blah Blah Blah",
    distance: "20 km",
    car: "15 min",
    bus: "50 min",
    bike: "20 min",
    walk: "1h 15 min",
    type: "trail",
  ),
  NearbyPlaceModel(
    image: "assets/places/DevilPunchbowlFalls.jpg",
    name: "Devil's Punchbowl Falls",
    description: "Blah Blah Blah",
    distance: "22 km",
    car: "15 min",
    bus: "50 min",
    bike: "20 min",
    walk: "1h 15 min",
    type: "waterfalls",
  ),
];
List<NearbyPlaceModel> nearbyPlacesCN = [
  NearbyPlaceModel(
    image: "assets/places/BayfrontPark.jpg",
    name: "岸前公园",
    description: "Blah Blah Blah",
    distance: "5 km",
    car: "15 min",
    bus: "50 min",
    bike: "20 min",
    walk: "1h 15 min",
    type: "park",
  ),
  NearbyPlaceModel(
    image: "assets/places/ChristieLake.jpg",
    name: "克里斯蒂湖",
    description: "Blah Blah Blah",
    distance: "8 km",
    car: "15 min",
    bus: "50 min",
    bike: "20 min",
    walk: "1h 15 min",
    type: "lake",
  ),
  NearbyPlaceModel(
    image: "assets/places/CootesParadiseTrail.jpg",
    name: "CP 小道",
    description: "Blah Blah Blah",
    distance: '2 km',
    car: "15 min",
    bus: "50 min",
    bike: "20 min",
    walk: "1h 15 min",
    type: "lake",
  ),
  NearbyPlaceModel(
    image: "assets/places/GagePark.jpg",
    name: "盖奇公园",
    description: "Blah Blah Blah",
    distance: "10 km",
    car: "15 min",
    bus: "50 min",
    bike: "20 min",
    walk: "1h 15 min",
    type: "park",
  ),
  NearbyPlaceModel(
    image: "assets/places/TiffanyFalls.jpg",
    name: "蒂芙尼瀑布",
    description: "Blah Blah Blah",
    distance: "15 km",
    car: "15 min",
    bus: "50 min",
    bike: "20 min",
    walk: "1h 15 min",
    type: "waterfalls",
  ),
  NearbyPlaceModel(
    image: "assets/places/WaterfrontTrail.jpg",
    name: "湖边小道",
    description: "Blah Blah Blah",
    distance: "20 km",
    car: "15 min",
    bus: "50 min",
    bike: "20 min",
    walk: "1h 15 min",
    type: "trail",
  ),
  NearbyPlaceModel(
    image: "assets/places/DevilPunchbowlFalls.jpg",
    name: "德芙瀑布",
    description: "Blah Blah Blah",
    distance: "22 km",
    car: "15 min",
    bus: "50 min",
    bike: "20 min",
    walk: "1h 15 min",
    type: "waterfalls",
  ),
];
